# Generated by Django 3.1.4 on 2020-12-15 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='energy_fruits',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='user',
            name='knowledge_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='VocabMCQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_language_word', models.CharField(max_length=40)),
                ('target_language_word', models.CharField(max_length=40)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_set', to='firstapp.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='VocabMCChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_choice', models.CharField(max_length=40)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choice_set', to='firstapp.vocabmcquestion')),
            ],
        ),
    ]
